bug fix) build error
> frontend@0.1.0 build
> react-scripts build

node:internal/modules/cjs/loader:1228
  throw err;
  ^

Error: Cannot find module 'ajv/dist/compile/codegen'
Require stack:
- /home/andold/src/github/ics/src/main/frontend/node_modules/ajv-keywords/dist/definitions/typeof.js
- /home/andold/src/github/ics/src/main/frontend/node_modules/ajv-keywords/dist/keywords/typeof.js
- /home/andold/src/github/ics/src/main/frontend/node_modules/ajv-keywords/dist/keywords/index.js
- /home/andold/src/github/ics/src/main/frontend/node_modules/ajv-keywords/dist/index.js
- /home/andold/src/github/ics/src/main/frontend/node_modules/schema-utils/dist/validate.js
- /home/andold/src/github/ics/src/main/frontend/node_modules/schema-utils/dist/index.js
- /home/andold/src/github/ics/src/main/frontend/node_modules/terser-webpack-plugin/dist/index.js
- /home/andold/src/github/ics/src/main/frontend/node_modules/react-scripts/config/webpack.config.js
- /home/andold/src/github/ics/src/main/frontend/node_modules/react-scripts/scripts/build.js
    at Module._resolveFilename
(node:internal/modules/cjs/loader:1225:15)
    at Module._load (node:internal/modules/cjs/loader:1051:27)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous>
(/home/andold/src/github/ics/src/main/frontend/node_modules/ajv-keywords/dist/definitions/typeof.js:3:19)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/andold/src/github/ics/src/main/frontend/node_modules/ajv-keywords/dist/definitions/typeof.js',
    '/home/andold/src/github/ics/src/main/frontend/node_modules/ajv-keywords/dist/keywords/typeof.js',
    '/home/andold/src/github/ics/src/main/frontend/node_modules/ajv-keywords/dist/keywords/index.js',
    '/home/andold/src/github/ics/src/main/frontend/node_modules/ajv-keywords/dist/index.js',
    '/home/andold/src/github/ics/src/main/frontend/node_modules/schema-utils/dist/validate.js',
    '/home/andold/src/github/ics/src/main/frontend/node_modules/schema-utils/dist/index.js',
    '/home/andold/src/github/ics/src/main/frontend/node_modules/terser-webpack-plugin/dist/index.js',
    '/home/andold/src/github/ics/src/main/frontend/node_modules/react-scripts/config/webpack.config.js',
    '/home/andold/src/github/ics/src/main/frontend/node_modules/react-scripts/scripts/build.js'
  ]
}

Node.js v20.17.0